//This file is generated by the init.py script during the cmake configuration process

typedef struct Vector
{
    float x, y;
} Vector;

float x_function (Vector vector) { return vector.y; }
float y_function (Vector vector) { return -.2f * vector.y - (9.8f / 8) * sin(vector.x); }

__kernel void update_particle_position_matrix
(
    __global Vector * particle_position_matrix_buffer
)
{
    int id = get_global_id(0);

    Vector v = { 8, 8 };

    particle_position_matrix_buffer[id] = v;
}
